tx_elevators/urls.py
from django.conf.urls import patterns, include, url
from django.views.decorators.gzip import gzip_page


from . import chart_views, views


urlpatterns = patterns('',
    url(r'^$', views.Landing.as_view(),
        name="home"),
    url(r'^building/$', gzip_page(views.BuildingsList.as_view()),
        name="building_list"),
    url(r'^building/(?P<elbi>\d+)-(?P<slug>[-\w]+)/$',
        views.BuildingView.as_view(),
        name="building_detail"),
    url(r'^about/$', views.About.as_view(),
        name='about'),

    # chart url patterns
    url(r'^chart/', include(patterns('',
        url(r'^elevatorlist/(?P<data>data.json)?$',
                gzip_page(chart_views.ElevatorList.as_view()),
                name='elevatorlist'),
        url(r'^locator/(?P<data>data.json)?$',
                gzip_page(chart_views.Locator.as_view()),
                name='locator'),
        url(r'^search/(?P<data>data.json)?$',
                gzip_page(chart_views.Search.as_view()),
                name='search'),
    ), namespace='chart')),
)

tx_elevators/models.py
from django.core.urlresolvers import reverse
from django.db import models
# from django.utils.text import slugify
from django.template.defaultfilters import slugify


class Building(models.Model):
    """Some place with an address that holds `Elevator` object(s)."""
    # LICNO
    elbi = models.IntegerField(
        u'Building Number',
        unique=True,
        help_text='The Building Number is a TDLR issued number.',
    )
    # BNAME1
    name_1 = models.CharField(max_length=100)
    # BNAME2
    name_2 = models.CharField(max_length=100, blank=True)
    # BADDR1
    address_1 = models.CharField(max_length=100)
    # BADDR2
    address_2 = models.CharField(max_length=100, blank=True)
    # BCITY
    city = models.CharField(max_length=50)
    # BZIP
    zip_code = models.CharField(max_length=5)
    # BCOUNTY
    county = models.CharField(max_length=20)
    # ONAME1
    owner = models.CharField(max_length=100)
    # CNAME1
    contact = models.CharField(max_length=100)

    # not using postgis for sqlite compatibility
    # google geocoder returns up to 7 decimals (1.11 cm precision)
    latitude = models.DecimalField(max_digits=10, decimal_places=7,
        null=True, blank=True)
    longitude = models.DecimalField(max_digits=10, decimal_places=7,
        null=True, blank=True)

    def __unicode__(self):
        return u"{0.name_1} in {0.city}".format(self)

    def get_absolute_url(self):
        return reverse('tx_elevators:building_detail',
            kwargs={'elbi': self.elbi, 'slug': slugify(self.name_1)})

    def get_geo_query(self):
        lookup_bits = []
        if self.address_1:
            lookup_bits.append(self.address_1)
        if self.city:
            lookup_bits.append(self.city)
        if not lookup_bits:
            return
        lookup = ', '.join(map(str, lookup_bits))
        return lookup

    def geocode(self, lookup=None, force=False):
        """
        Geocode this building.

        Latitudes should be between 25 50' and 36 30'
        Longitude should be between -93 31' and -106 39'
        """
        from geopydb import geocoders
        g = geocoders.GoogleV3()
        # XXX the zip code is wrong sometimes
        __, (lat, lng) = g.geocode(self.get_geo_query(), exactly_one=True,
            components=dict(
                postal_code=self.zip_code,
            ),
            force=force,
        )
        self.latitude = lat
        self.longitude = lng
        self.save()

    def neighbors(self, d=0.001):
        """
        Get neighboring buildings.

        Defaults to a very tiny radius.
        """
        return Building.objects.filter(
            latitude__range=(self.latitude - d, self.latitude + d),
            longitude__range=(self.longitude - d, self.longitude + d),
        )

    def ungeocode(self):
        """
        Mark this geocode as wrong.
        """
        for building in self.neighbors():
            building.geocode(force=True)


class ElevatorManager(models.Manager):
    use_for_related_fields = True

    def for_table(self):
        """
        The queryset that should be used inside the building_detail template.
        """
        return self.get_queryset().order_by(
            '-floors',
            '-equipment_type',
            'drive_type',
        )


class Elevator(models.Model):
    """Something humans use to go up a `Building`."""
    # IDNO
    tdlr_id = models.IntegerField(
        u'Texas Department of Licensing and Regulation ID',
    )
    # SUB_NO
    decal = models.IntegerField(
        u'Equipment Identification Number',
        unique=True,
        help_text=('Decal# is a TDLR number issued to a particular elevator or'
                   ' piece of equipment.')
    )
    # DT_CRT_INS
    last_inspection = models.DateField(
        u'Date of Last Certified Inspection',
        null=True,
    )
    # DT_EXPIRY
    next_inspection = models.DateField(
        u'Date of Next Inspection',
        # may be null for time traveling future elevators
        null=True,
    )
    # ELV_5YEAR
    last_5year = models.DateField(
        u'Date of Last 5 Year Test',
        null=True,
    )
    # EQUIPMENT_TYPE
    # choices:
    # [u'ESCALATOR',
    #  u'NEW EQUIPMENT',
    #  u'STAIR CLIMBER',
    #  u'ELECTRIC ELEVATOR',
    #  u'LIMITED USE LIMITED ACCESS',
    #  u'FREIGHT',
    #  u'WHEELCHAIR LIFT',
    #  u'UNKNOWN',
    #  u'HYDRAULIC ELEVATOR',
    #  u'OTHER',
    #  u'PASSENGER',
    #  u'MOVING SIDEWALK']
    equipment_type = models.CharField(
        u'Equipment Type',
        # TODO choices
        max_length=26,
    )
    # DRIVE_TYPE
    # choices:
    # [u'ELEVATOR DRIVE TYPE',
    #  u'CHAIN',
    #  u'ELECTRIC',
    #  u'UNKNOWN',
    #  u'ROPED SPROCKET',
    #  u'ROPED HYDRAULIC',
    #  u'SCREW',
    #  u'HYDRAULIC',
    #  u'RACK & PINION',
    #  u'WINDING DRUM']
    drive_type = models.CharField(
        u'Machine Drive Type',
        # TODO choices
        max_length=20,
    )
    # FLOORS
    floors = models.IntegerField()
    # YR_INSTALL
    year_installed = models.IntegerField()

    building = models.ForeignKey(Building)

    # managers
    objects = ElevatorManager()

    def __unicode__(self):
        return u"{0.building} {0.floors} ({0.year_installed})".format(self)

    @property
    def css_classes(self):
        return self.equipment_type.split(' ')[0].lower()

tx_elevators/templates/tx_elevators/about.html
{% extends "tx_elevators/layouts/base.html" %}
{% load humanize %}

{% block head_title %}About{% endblock %}
{% block page_title %}About{% endblock %}


{% block main %}
  <section>
    <h3>Stats at a Glance</h3>
    <dl class="dl-horizontal">
      <dt>Buildings</dt>
      <dd>{{ buildings.count|intcomma }}</dd>
      <dt>Total Elevators</dt>
      <dd>{{ elevators.count|intcomma }}</dd>
      <dt>Passenger Elevators</dt>
      <dd>{{ passenger_elevators.count|intcomma }}</dd>
      <dt>Freight Elevators</dt>
      <dd>{{ freight_elevators.count|intcomma }}</dd>
      <dt>Escalators</dt>
      <dd>{{ escalators.count|intcomma }}</dd>
      <dt>Moving Sidewalks</dt>
      <dd>{{ moving_sidewalks.count|intcomma }}</dd>
    </dl>
  </section>

  <section>
    <h3>The Data</h3>
    <p>
      Elevator data is available courtesy the Texas Department of Licensing and
      Regulation. To learn more about the data and download the original, visit
      the

      <a href="https://www.license.state.tx.us/ElevatorSearch/HelpPage.asp#data" target="_blank">
        elevator search help page
      </a>.
    </p>
    <p>

      The data isn't perfect. For example, there are {{ future.count|apnumber }}
      elevators listed as being installed after {% now "Y" %}:

      {% for elevator in future %}
        {% if not forloop.last %}
          <a href="{{ elevator.building.get_absolute_url }}">{{ elevator }}</a>.
        {% else %}
          and <a href="{{ elevator.building.get_absolute_url }}">{{ elevator }}</a>
        {% endif %}
      {% endfor %}

      And there are {{ past.count }} elevators that were installed before the
      year 1000.

    </p>
    <p>
      <small>Data current as of {% now "Y-m-d" %}</small>
    </p>
  </section>

  <section>
    <h3>Location</h3>
    <p>

      The maps are presented in Google Maps because they have buildings when you
      zoom in. Using Google Maps also allowed me to use their geocoder. The data
      is only partially geocoded. Only {{ geocoded.count|intcomma }} out of
      {{ buildings.count|intcomma }} buildings have been geocoded and show up the
      map. And of the geocoded buildings, many have inaccurate locations.

    </p>
  </section>

  <section>
    <h3>Code</h3>
    <p>

      The code for this site is available under an open source license at
      <a href="https://github.com/texas/tx_elevators" target="_blank">GitHub</a>.
      It was coded over a few nights and most of a
      <a href="https://github.com/texas/tx_elevators/graphs/punch-card" target="_blank">weekend</a>
      by a programmer from
      <a href="https://www.texastribune.org/about/staff/" target="_blank">The Texas Tribune</a>.

    </p>
  </section>
{% endblock %}

tx_elevators/templates/tx_elevators/building_detail.html
{% extends "tx_elevators/layouts/base.html" %}

{% block head_title %}{{ object }}{% endblock %}
{% block page_title %}{{ object }}{% endblock %}
{% block og_title %}{{ object }}{% endblock %}

{% block main %}
  <dl id="building-data" class="dl-horizontal" data-building='{"latitude": {{ object.latitude }}, "longitude": {{ object.longitude }}}'>
    <dt>Building Number</dt>
    <dd>ELBI-{{ object.elbi }}</dd>
    <dt>Name</dt>
    <dd>
      {{ object.name_1 }}
      {{ object.name_2 }}
    </dd>
    <dt>Address</dt>
    <dd>
      {{ object.address_1 }}
      {{ object.address_2 }}
      {{ object.city }}, {{ object.zip_code }}
    </dd>
    <dt>Owner</dt>
    <dd>{{ object.owner }}</dd>
    <dt>Contact</dt>
    <dd>{{ object.contact }}</dd>
  </dl>

  <h2>Elevators</h2>
  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>Equipment ID</th>
        <th>Last Certified Inspection</th>
        <th>Equipment Type</th>
        <th>Drive Type</th>
        <th>Floors</th>
        <th>Year Installed</th>
      </tr>
    </thead>
    <tbody>
      {% for elevator in object.elevator_set.for_table %}
        <tr class="{{ elevator.css_classes }}">
          <td>{{ elevator.decal }}</td>
          <td>{{ elevator.last_inspection }}</td>
          <td>{{ elevator.equipment_type }}</td>
          <td>{{ elevator.drive_type }}</td>
          <td>{{ elevator.floors }}</td>
          <td>{{ elevator.year_installed }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a class="prefetch-hint" href="{% url 'tx_elevators:chart:search' %}" rel="nofollow" style="display: none;"></a>

  <div id="disqus_thread"></div>
  <script>
  /**
  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
  var disqus_config = function () {
    this.page.identifier = '{{ object.elbi }}';
  };
  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = '//tx-elevators.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
  })();
  </script>

{% endblock %}

tx_elevators/templates/tx_elevators/building_list.html
{% extends "tx_elevators/layouts/base.html" %}


{% block head_title %}Buildings{% endblock %}
{% block page_title %}Buildings{% endblock %}
{% block body_class %}search{% endblock %}


{% block main %}
  <section class="show-for-nojs">
    <ol class="buildings">
      {% for object in object_list %}
        <li id="elbi-{{ object.elbi }}" class="building" data-elbi="{{ object.elbi }}">
          <a href="{{ object.get_absolute_url }}">{{ object }}</a>
        </li>
      {% endfor %}
    </ol>
  </section>

  <section id="search-container" class="hide-for-nojs">
    <h2>Search:</h2>
    <div class="row">
      <div class="span8 offset2">
        <input id="q" class="span8" type=text placeholder="Name">
      </div>
    </div>
    <h3>Group Results By:</h3>
    <ul class="nav nav-tabs">
      <li class="active"><a href="#buildingName">Name</a></li>
      <li><a href="#city">City</a></li>
      <li><a href="#zip">Zip</a></li>
      <li class="offset1">
        <button id="show-all" class="btn" type=button title="Use with caution"><i class="icon-list"></i> Show All</button>
      </li>
    </ul>
    <div id="name" class="row loading"></div>
  </section>
{% endblock %}


{% block extra_script %}{{ block.super }}
  <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.0.8/d3.min.js"></script>
  <a class="prefetch-hint" href="{% url 'tx_elevators:chart:search' %}data.json" rel="nofollow" style="display: none;"></a>
  <script src="{{ STATIC_URL }}tx_elevators/js/search.js"></script>
{% endblock %}

tx_elevators/templates/tx_elevators/landing.html
{% extends "tx_elevators/layouts/base.html" %}

{% block head_title %}Elevator Explorer{% endblock %}
{% block page_title %}Elevator Explorer <small>How Texans are Raised</small>{% endblock %}


{% block main %}
<section>
  <h2>Tallest Buildings</h2>
  <ol>
    {% for building in tallest_buildings %}
      <li>
        <a href="{{ building.get_absolute_url }}">{{ building }}</a>
        &ndash; {{ building.height }} floors
      </li>
    {% endfor %}
  </ol>
</section>

<section>
  <h2>Oldest Elevators</h2>
  <ol>
    {% for elevator in oldest_elevators %}
      <li><a href="{{ elevator.building.get_absolute_url }}">
        {{ elevator.building }}</a>
        &ndash; installed in {{ elevator.year_installed }}
      </li>
    {% endfor %}
  </ol>
</section>

<section>
  <h2>Buildings with the Most Elevators</h2>
  <ol>
    {% for building in densest_buildings %}
      <li>
        <a href="{{ building.get_absolute_url }}">{{ building }}</a>
        &ndash; {{ building.num_elevators }} elevators
      </li>
    {% endfor %}
  </ol>
</section>

<section>
  <h2>Distribution of Age and Floors of Elevators</h2>
  <div class="chart" data-src="{% url 'tx_elevators:chart:elevatorlist' %}">
    <noscript>
      Missing Figure
    </noscript>
  </div>
  <a class="prefetch-hint" href="{% url 'tx_elevators:chart:elevatorlist' %}" rel="nofollow" style="display: none;"></a>
</section>
{% endblock %}